class ContactDetailsPage:

    lnk_contact_details  = "//a[normalize-space()='Contact Details']"
    lnk_login_info       = "//a[normalize-space()='Login Info']"
    txt_street1          = "//label[text()='Street 1']/following::input[contains(@class,'oxd-input')][1]"
    txt_street2          = "//label[text()='Street 2']/following::input[1]"
    txt_city             = "//label[text()='City']/following::input[1]"
    txt_state            = "//label[text()='State/Province']/following::input[1]"
    txt_zip              = "//label[text()='Zip/Postal Code']/following::input[1]"
    drp_country          = "//label[text()='Country']/following::div[1]"
    option_text          = "//div[@role='listbox']//span"
    txt_home_telephone   = "//label[text()='Home']/following::input[1]"
    txt_mobile           = "//label[text()='Mobile']/following::input[1]"
    txt_work_telephone   = "//label[text()='Work']/following::input[1]"
    txt_work_email       = "//label[text()='Work Email']/following::input[1]"
    btn_save             = "(//div[contains(@class,'orangehrm-card-container')])[1]//button[normalize-space()='Save']"
    msg_success          = "//div[contains(@class,'oxd-toast-content')]//p[1]"
    btn_add_attachment   = "//h6[text()='Attachments']/following::button[1]"
    inp_file_upload      = "//input[@type='file']"
    btn_save_attachment  = "//div[contains(@class,'orangehrm-attachment')]//button[normalize-space()='Save']"
    load_spinner         = "//div[contains(@class,'oxd-loading-spinner-container')]"