class MyInfoPage:

    lnk_personal_details   = "//a[normalize-space()='Personal Details']"
    txt_license_expiry     = "//label[text()='License Expiry Date']/following::input[1]"
    option_text            = "//div[@role='option']//span"
    drp_nationality        = "//label[text()='Nationality']/following::div[contains(@class,'oxd-select-text')][1]"
    drp_marital_status     = "//label[text()='Marital Status']/following::div[contains(@class,'oxd-select-text')][1]"
    rdo_male               = "//label[normalize-space()='Male']"
    rdo_female             = "//label[normalize-space()='Female']"
    btn_save               = "//button[contains(@class,'oxd-button--secondary') and contains(@class,'orangehrm-left-space')]"
    msg_success            = "//div[@class='oxd-toast-content oxd-toast-content--success']"
    load_spinner           = "//div[contains(@class,'oxd-loading-spinner-container')]"
    blood_type             = "//label[text()='Blood Type']/following::div[contains(@class,'oxd-select-text')][1]"
    test_field             = "//label[text()='Test_Field']/following::input[1]"
    btn1_save              = "(//button[normalize-space()='Save'])[1]"
    msg1_success           = "//div[contains(@class,'oxd-toast')]//p[contains(@class,'oxd-text')]"
    btn_add_attachment     = "//button[@class='oxd-button oxd-button--medium oxd-button--text']"
    inp_file_upload        = "//input[@type='file']"
    txt_attachment_desc    = "//textarea[@placeholder='Type comment here']"
    btn_save_attachment    = "(//button[normalize-space()='Save'])[last()]"
    msg_attachment_success = "//div[contains(@class,'oxd-toast')]//p[contains(@class,'oxd-text')]"
    file_size_exceed       = "//span[text()='Attachment Size Exceeded']"